Fixed build error after Python was updated to 3.12.
Error: /usr/include/python3.12/cpython/listobject.h:34: PyList_GET_SIZE: Assertion `PyList_Check(op)' failed.
Alternative is to set DISABLE_LOGBOOK_CEXT environment variable to 1 in module build options.